[tools]
go = "1.23.2"

[env]
GOTOOLCHAIN = "local"

[tasks.install-air]
description = "Airをインストール"
run = "go install github.com/air-verse/air@latest"

[tasks.dev]
description = "開発モードで実行（ホットリロード）"
depends = ["install-air"]
run = "air"

[tasks.install-deps]
description = "Go依存関係をダウンロード"
run = "go mod download"

[tasks.build]
description = "サーバーバイナリをビルド"
run = "go build -o ./bin/server ./cmd/server"

[tasks.run]
description = "ビルド済みバイナリを実行"
depends = ["build"]
run = "./bin/server"

[tasks.test]
description = "テストを実行"
run = "go test -v ./..."

[tasks.clean]
description = "生成物をクリーンアップ"
run = "rm -rf ./bin ./tmp"

[tasks.install-flyctl]
description = "Fly.io CLIをインストール"
run = "curl -L https://fly.io/install.sh | sh"

[tasks.fly-login]
description = "Fly.ioにログイン"
run = "fly auth login"

[tasks.fly-launch]
description = "Fly.ioアプリを既存設定から作成"
depends = ["fly-login"]
run = "fly launch --copy-config --no-deploy --yes"

[tasks.fly-deploy]
description = "Fly.ioへデプロイ"
depends = ["fly-login"]
run = "fly deploy --strategy rolling --wait-timeout 300"

[tasks.fly-status]
description = "Fly.ioのアプリ稼働状況を確認"
depends = ["fly-login"]
run = "fly status"

[tasks.fly-secrets]
description = "Fly.ioシークレットを登録"
depends = ["fly-login"]
shell = true
run = '''
set -e
if [ -z "${SECRET:-}" ]; then
  echo 'SECRET環境変数に設定値を指定してください (例: SECRET="DATABASE_URL=... APP_URL=..." mise run fly-secrets)'
  exit 1
fi
set -f
set -- $SECRET
fly secrets set "$@"
'''
