app = "okusuri-backend"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  GIN_MODE = "release"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

[[checks]]
  name = "healthcheck"
  type = "http"
  port = 8080
  interval = "30s"
  timeout = "5s"
  path = "/api/health"
  grace_period = "15s"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
